/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PaginationComponent {
        "changePage": any;
        "currentPage": number;
        "getPaginationGroup": any;
        "goToNextPage": any;
        "goToPreviousPage": any;
        "pages": number;
    }
    interface SearchComponent {
        "setDefaultData": any;
        "updateList": any;
    }
    interface TableComponent {
        "currentPage": number;
        "data": any;
        "invokeCallback": any;
        "limit": number;
        "tHeads": any[];
        "total": number;
    }
}
declare global {
    interface HTMLPaginationComponentElement extends Components.PaginationComponent, HTMLStencilElement {
    }
    var HTMLPaginationComponentElement: {
        prototype: HTMLPaginationComponentElement;
        new (): HTMLPaginationComponentElement;
    };
    interface HTMLSearchComponentElement extends Components.SearchComponent, HTMLStencilElement {
    }
    var HTMLSearchComponentElement: {
        prototype: HTMLSearchComponentElement;
        new (): HTMLSearchComponentElement;
    };
    interface HTMLTableComponentElement extends Components.TableComponent, HTMLStencilElement {
    }
    var HTMLTableComponentElement: {
        prototype: HTMLTableComponentElement;
        new (): HTMLTableComponentElement;
    };
    interface HTMLElementTagNameMap {
        "pagination-component": HTMLPaginationComponentElement;
        "search-component": HTMLSearchComponentElement;
        "table-component": HTMLTableComponentElement;
    }
}
declare namespace LocalJSX {
    interface PaginationComponent {
        "changePage"?: any;
        "currentPage"?: number;
        "getPaginationGroup"?: any;
        "goToNextPage"?: any;
        "goToPreviousPage"?: any;
        "pages"?: number;
    }
    interface SearchComponent {
        "setDefaultData"?: any;
        "updateList"?: any;
    }
    interface TableComponent {
        "currentPage"?: number;
        "data"?: any;
        "invokeCallback"?: any;
        "limit"?: number;
        "tHeads"?: any[];
        "total"?: number;
    }
    interface IntrinsicElements {
        "pagination-component": PaginationComponent;
        "search-component": SearchComponent;
        "table-component": TableComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pagination-component": LocalJSX.PaginationComponent & JSXBase.HTMLAttributes<HTMLPaginationComponentElement>;
            "search-component": LocalJSX.SearchComponent & JSXBase.HTMLAttributes<HTMLSearchComponentElement>;
            "table-component": LocalJSX.TableComponent & JSXBase.HTMLAttributes<HTMLTableComponentElement>;
        }
    }
}
